### ISSUE TITLE
Please update the version in the Chrome Web Store

### ISSUE THREAD

**Issue by kankaristo** [metarmask/tab-playlist#5]
The Web Store version freezes Chrome after extended use, because `content-script.js` has an old extension ID (which changes in every version, I guess?).

This breaks the detection of whether the script has already been injected, and each instance seems to inject itself again and again, so first there's 1 script injected, then 2, then 4, 8, 16, etc. This spirals out of control, and eventually Chrome gets stuck.

This already seems to be fixed in the Git version, so please release the latest version in the Chrome Web Store!

BTW, could you add the URL for this repository into the Chrome Web Store description? The Web Store hides it pretty well (it's under "Support" and there's a teeny-tiny link for "support site"). I almost didn't find the repo, and the Web Store is a terrible place for filing issues.

And thank you for a very useful extension! :+1:

**Comment by metarmask** [comment]
Thanks for letting me know. I've updated the extension in the store.

Regarding the link to the repository: I have added the URL as the "web page" for the extension, making it slightly more prominent. URLs do not become links in the description, which is why I don't want to put it there.

**Comment by kankaristo** [comment]
Wow, that was fast! Thanks! :tada:

The new version isn't visible for me yet, but there's probably just a small delay until it will be.

**Comment by kankaristo** [comment]
Seems to be fixed now, thank you!
